mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    cn.vipwen.stream_mybatis.mapper: debug
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/goods?characterEncoding=utf8&verifyServerCertificate=false&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root